# Generated by Django 5.2.4 on 2025-07-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptons',
            new_name='symptoms',
        ),
    ]
